### PR TITLE
Added support for licenses with AND and OR

### PR DESCRIPTION
**Pull request by nicolamarella**
Should be a solution for https://github.com/pivotal/LicenseFinder/issues/728

Althouhg for now only working when using `find_by_name`. Probably should be done for `find_by_text` too.
Anyway, for `find_by_text` it will still return the same result as it did before, thus failing in the AND/OR case, but will not cause errors.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@nicolamarella Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=755)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=755) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@nicolamarella Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=755)!

**Comment by xtreme-shane-lattanzio** [comment]
Hey @nicolamarella ! Thanks for the PR. Could you please make the rubocop fixes found by our pipeline? Then we can have it merged in :)

**Comment by nicolamarella** [comment]
Hi @xtreme-shane-lattanzio
all the issues should be now resolved. Thanks!

**Pull request merged**
