### PR TITLE
Introduces support for Elixir projects (using Mix)

### PR DESCRIPTION
**Pull request by bdshroyer**
Signed-off-by: Sam Coward <idoru42@gmail.com>

### CODE REVIEW

**Comment by connorshea** [comment]
Relevant issue: #253.

Tests are failing!

**Comment by flavorjones** [comment]
@bdshroyer -- Thanks for submitting this!

Is it worth squashing some or all of these commits, do you think? I haven't read the commit history in detail yet, so "no" is an OK answer.

**Comment by bdshroyer** [comment]
@flavorjones Probably, yeah. I hadn't counted on all the extra noise from the rebase, but I had been planning to squash those commits anyway once I had something that could pass Travis.

**Comment by pivotal-issuemaster** [comment]
@bdshroyer Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=261)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=261) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@bdshroyer Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=261)!

**Pull request merged**
