### PR TITLE
Bundler CLI package manager is now present

### PR DESCRIPTION
**Pull request by Fire-Dragon-DoL**
This PR is to initiate a discussion.
It adds a new Package manager called "Bundler CLI" which as suggested, uses bundler as a CLI tool, not as a ruby library.
This approach treats bundler like every other package manager, eliminating a big category of errors caused by loading bundler in the same process where `license_finder` is executed. Notice this problem can't happen for non-ruby package managers.

An alternative approach to this would be forking within license finder and only then execute Bundler-related operations, with some IPC mechanism to return the result.

This CLI approach has the downside of paying the "ruby initiation" cost repeatedly, which results in some serious slowdowns when dealing with a lot of dependencies. Using `Parallel` provides substantial relief, at the cost of spinning fans.

I wrote this code after encountering a blocking bug (https://github.com/pivotal/LicenseFinder/issues/838) when dealing with `bundle install --path something`, where `license_finder` would attempt to load bundler and fail to find any gems because not executed with bundle exec, but it would also fail with bundle exec because it's not part of the bundle and cannot be part of the bundle due to a dependency conflict.

## TODO

- [ ] Help update
- [ ] Tests
- [ ] Support `--bundler-options`

### CODE REVIEW

**Comment by xtreme-shane-lattanzio** [comment]
Hey @Fire-Dragon-DoL ! Thanks for this work. The bundler pathing issues is something that has always plagued us. It has gone through many different iterations to try to solve all cases. We have environment variables for gemfile path and have tried to customize the gem_path in the prepare command. I think https://github.com/pivotal/LicenseFinder/issues/828 may be related and he found a workaround for the gem path.

Normally I would be against this alternative kind of approach but since there are so many issues with this, I would be fine with adding this as some kind of `beta` feature. Have you looked into the gem_path stuff on line 30 of bundler.rb? Or is that not close to this problem?

**Comment by Fire-Dragon-DoL** [comment]
hey @xtreme-andy-shen thanks for reading my PR.
I tried really hard to get that approach working, but I was already running (manually) `bundle install --vendor/bundle`, which made that fix irrelevant (although I did try it).

I think that in most cases, the problem is that those tests are performed in a state where the gems are also installed globally first (raw `bundle install`) and then `bundle install --path`, so the gems are in both locations.
I can't confirm this though.

That being said, bundler is built in a way intended to alter the _current_ (global) ruby environment so that it's isolated from the rest of the world, given this premise, it makes sense that LF is having so many problems with it.

The approach I used is "ugly" for a ruby package (should be able to invoke it from within Ruby), but seen from the perspective of the other package managers, it makes sense: they are all used through CLI.

If we want to use bundler directly and avoid issues, I think the ideal approach is to isolate bundler within Ruby: that is, fork.
This will separate and isolate the two processes, so it should be possible to run bundler in one without "breaking" LF.

This PR is indeed intended as beta. It works "flawlessly" (I'm the only one who tested it, so I can say very little about it) with bundler though, so it can solve the problem for a lot of people while we get to a better state.
The core problem is identifying the better state: is **fork** the right approach? If not, what would it be?
I was hoping to discuss this so that I can improve the PR.

Cheers!

**Comment by Fire-Dragon-DoL** [comment]
hey @xtreme-shane-lattanzio thanks for reading my PR.
I tried really hard to get that approach working, but I was already running (manually) `bundle install --vendor/bundle`, which made that fix irrelevant (although I did try it).

I think that in most cases, the problem is that those tests are performed in a state where the gems are also installed globally first (raw `bundle install`) and then `bundle install --path`, so the gems are in both locations.
I can't confirm this though.

That being said, bundler is built in a way intended to alter the _current_ (global) ruby environment so that it's isolated from the rest of the world, given this premise, it makes sense that LF is having so many problems with it.

The approach I used is "ugly" for a ruby package (should be able to invoke it from within Ruby), but seen from the perspective of the other package managers, it makes sense: they are all used through CLI.

If we want to use bundler directly and avoid issues, I think the ideal approach is to isolate bundler within Ruby: that is, fork.
This will separate and isolate the two processes, so it should be possible to run bundler in one without "breaking" LF.

This PR is indeed intended as beta. It works "flawlessly" (I'm the only one who tested it, so I can say very little about it) with bundler though, so it can solve the problem for a lot of people while we get to a better state.
The core problem is identifying the better state: is **fork** the right approach? If not, what would it be?
I was hoping to discuss this so that I can improve the PR.

Cheers!

**Comment by Fire-Dragon-DoL** [comment]
@xtreme-shane-lattanzio This is an alternative approach to what I provided here. It's substantially faster and accesses Bundler through ruby, however it does so by running a separate ruby executables. Overall, the downsides seem minimal and solves an existing bug: https://github.com/pivotal/LicenseFinder/pull/843

**Comment by xtreme-shane-lattanzio** [comment]
Closing in favour of https://github.com/pivotal/LicenseFinder/pull/843

**Pull request closed without merging**
