### PR TITLE
Support of Conan v1.6 and v2

### PR DESCRIPTION
**Pull request by melter2m**
## Motivation
Conan 1.6 extracts licenses to different path than expected which causes License Finder to crash.

### Reason
File mask that is used to search licenses looks as follows:

`#{project_path}/licenses/#{name}/**/LICENSE*`

Conan 1.6 creates license files under `#{project_path}/licenses/#{name}/licenses/LICENSE*` and first file that suites is directory

### Solution

Iterate over the files that suite mentioned above mask until we find not directory

### CODE REVIEW

**Comment by xtreme-shane-lattanzio** [comment]
Hey @melter2m ! Thanks for the PR! We are working on getting the jammy image upgrade since it is causing all kinds of issues right now. Once thats in, hopefully the pipelines on this PR pass and we will merge it in!!

**Comment by xtreme-shane-lattanzio** [comment]
Hey @melter2m ! It looks like these changes do actually fail a test. Can you take a look and fix so we can have this merged in?

**Comment by melter2m** [comment]
> 

Fixed

**Comment by melter2m** [comment]
> Hey @melter2m ! It looks like these changes do actually fail a test. Can you take a look and fix so we can have this merged in?

fixed

**Pull request merged**
