### PR TITLE
Add support of gems.rb/gems.locked files

### PR DESCRIPTION
**Pull request by n-rodriguez**
Thank you!

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@n-rodriguez Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=817)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=817) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@n-rodriguez Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=817)!

**Comment by n-rodriguez** [comment]
> I don't know much about this gems.locked file

https://github.com/rubygems/bundler/issues/694

**Comment by n-rodriguez** [comment]
@xtreme-shane-lattanzio I've fixed the bug so CI should be green now.

> I don't know much about this gems.locked file but we will need to make sure we have tests to cover all these cases.

I think it's already the case. See: https://github.com/ruby/setup-ruby/pull/84#issuecomment-687349690



> Please take a look at adding some tests when you have a chance!

I'd like to but :

```sh
nicolas@tchoum-laptop:~/PROJECTS/GITHUB/LicenseFinder$ bundle exec rake
LicenseFinder::GoDep: is not installed
LicenseFinder::Glide: is not installed
LicenseFinder::Gvt: is not installed
LicenseFinder::Govendor: is not installed
LicenseFinder::Dep: is not installed
LicenseFinder::Pip: is not installed
LicenseFinder::Bower: is not installed
LicenseFinder::Maven: is not installed
LicenseFinder::Gradle: is not installed
LicenseFinder::Rebar: is not installed
LicenseFinder::Nuget: is not installed
LicenseFinder::Mix: (elixir) is not installed
LicenseFinder::Sbt: is not installed
LicenseFinder::Dotnet: is not installed
```

**Comment by xtreme-shane-lattanzio** [comment]
@n-rodriguez Thanks for getting this green! As for the missing installations, the best way to get that running is by using the LicenseFinder docker image. That will guarantee that you have everything installed that you need to. Try out the Docker section in the readme and let me know if you need any help!

**Comment by n-rodriguez** [comment]
> try out the Docker section in the readme and let me know if you need any help!

I won't have time for this, so can you please merge it?

**Pull request closed without merging**
