### PR TITLE
Feature: Copyright detection

### PR DESCRIPTION
**Pull request by forelabs**
We need a copyright notice detection for our reports. While we have this already as a patch it might be useful for others too. This would also solve https://github.com/pivotal/LicenseFinder/issues/315

Opened as a draft for discussion - if it is clear that it might get merged I will add specs.
I would like to know what you think about that.

Here is a small screenshot to give you a hint how it could look like:

image

### CODE REVIEW

**Comment by xtreme-shane-lattanzio** [comment]
@forelabs I see no reason not to include this functionality. In our own internal systems, we actually use a combination of LF and Fossology to find things such as copyrights and combine the data. This is a great step to get at least the base copyright from dedicated files. This would also not change current functionality as it will only activate if someone specifies a column to do so so this will not confuse current users. I really appreciate the input on this and thanks for contributing to the issue attached!

**Comment by forelabs** [comment]
FYI: I will continue working on this end of week or next week

**Comment by xtreme-shane-lattanzio** [comment]
Hey @forelabs I just wanted to let you know that I am preparing to release a new version of LF. No rush on this PR but thought you should know.

One ask I have for the future is to prepend you commit messages with `[ADDED]` or something similar as outlined here: https://keepachangelog.com/en/1.0.0/. We have scripts that auto generate release notes from this. Don't worry about your past PRs as I have already created the messaging for them. Thanks!!

**Comment by forelabs** [comment]
@xtreme-shane-lattanzio sorry we had a day off here in germany and I wasn't able to work a lot torday on that topic but started already with some specs. I hope I can wrap it up on monday.

**Comment by pivotal-pmital** [comment]
hello @forelabs! maybe I am missing something, but can you help me understand how do we get access to this feature using our CLI? Is there a new command for it? Or is this a new param for `--columns` flag?

**Comment by forelabs** [comment]
Hey, I missed the csv export part. Will add that tomorrow. Thanks for the hint.

**Comment by pivotal-pmital** [comment]
hey @forelabs, so I ran LF command `license_finder report -p --columns=name version install_path copyrights` against a sample project and I get an output like this (trimmed version)

```
pytest, 3.3.0, ""
ruamel.ordereddict, 0.4.14, ""
ruamel.yaml, 0.15.47, ""
setuptools, 44.1.0, "copyright__,, copyright__, Copyright (c) 2003-2018  Paul T, Copyright (c) 2010-2015 Benjamin Peterson"
six, 1.11.0, ""
```
When I examined the second last row in there, I noticed 2 things:
1. I see an entry for copyrights with empty string denoted by `,,`.
2. I see values like `copyright__`.

Also, from what I understood in the PR, I thought that it would only look at a subset of files defined by `CANDIDATE_FILE_NAMES` but from the looks of it, it is searching for the text in files outside of those candidates too. Am I missing something here? 😅

**Comment by pivotal-pmital** [comment]
Ahh mevermind, I just saw what's happening in `detect_in_path_files` method that you created. Alright, now the second part of my question makes sense. I am still wondering about the `,,` and `copyright__` values as shown in the last comment 😅

**Comment by forelabs** [comment]
> I am still wondering about the `,,` and `copyright__` values as shown in the last comment 😅 

Thanks for your feedback, I will try to improve the lookup. Currently in vacation so I may continue on this next week.

**Comment by forelabs** [comment]
Sorry to let you wait but currently I have a more important task within our team so I can not work on that feature improvement right now. I hope im able to do this in two weeks, last week of June will be used to finalize different work.
So not forgotten about this, just rescheduled according to our needs.

**Comment by xtreme-shane-lattanzio** [comment]
Hey @forelabs ! I just wanted to follow up on this since its been a while. Are there any plans to continue work on this PR and address the comments? Let us know if you want to go over it again. Thanks!!

**Comment by forelabs** [comment]
@xtreme-shane-lattanzio Hi, thanks for getting back to me. I am sorry but it seems that the importance of putting more work into the current tooling is not on our priority and I have to focus on different stuff. If you want I can close it for now and re open once we are coming back to this topic. And of course as always feel free to take over (or someone else) :slightly_smiling_face:

**Comment by xtreme-shane-lattanzio** [comment]
Closing due to inactivity. Feel free to reopen when this can be worked on!

**Comment by xtreme-shane-lattanzio** [comment]
Closing due to inactivity. Feel free to reopen when this can be worked on!

**Pull request closed without merging**
