### PR TITLE
Updating License Definitions

### PR DESCRIPTION
**Pull request by tourea**
Updated License Definitions
* Added CCDL1.0
* Added more aliases

### CODE REVIEW

**Comment by xtreme-shane-lattanzio** [comment]
@tourea Thanks for the PR! It looks like tests are failing because the file name does not match the short name specified. I recommend that the short name be updated to fix this. Let us know if you have any questions!

**Comment by tourea** [comment]
@xtreme-shane-lattanzio Could you provide more guidance?

**Comment by xtreme-shane-lattanzio** [comment]
@tourea Well that was annoying lol check out our latest commit on this PR. Apparently there was a special character in there that was messing with encoding so its rerunning now!

**Comment by tourea** [comment]
@xtreme-shane-lattanzio Can you merge it please?

**Comment by xtreme-shane-lattanzio** [comment]
Bumping for webhook trigger.

**Comment by pivotal-issuemaster** [comment]
@tourea Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=624)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=624) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Pull request merged**
