### PR TITLE
fix Rakefile

### PR DESCRIPTION
**Pull request by micfan**

### CODE REVIEW

**Comment by mainej** [comment]
What problem does this fix?  It breaks tests on Travis CI: `NameError: uninitialized constant RSpec`.

**Comment by micfan** [comment]
@mainej I don't know why the CI failed, but my local master branch, whoes rake command failed with the  follow:
``` bash
mic@mbp: ~/vm/LicenseFinder$ git last
commit fefa5da91ba95160d962a254c7a38cb3b8458176
Author: Jacob Maine <jacob.maine@gmail.com>
Date:   Tue Jul 28 21:36:28 2015 -0700

    document potentially dead code

mic@mbp: ~/vm/LicenseFinder$ rake
rake aborted!
LoadError: cannot load such file -- rspec/core/rake_task
/Users/mic/vm/LicenseFinder/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)

mic@mbp: ~/vm/LicenseFinder$ git br
  fix-rakefile
* master
```
And I can't find the file path: `require 'rspec/core/rake_task'`, so remove it to check package managers.

**Comment by mainej** [comment]
Weird. I can't merge this, because it breaks CI and doesn't work locally on my machine.  But I can try to help... What's your load path?  You can find it if you put `puts $LOAD_PATH` near the top of your Rakefile.

**Comment by micfan** [comment]
``` bash
mic@ubuntu:~/vm/LicenseFinder$ git remote -v
origin	https://github.com/PCF-License/LicenseFinder.git (fetch)
origin	https://github.com/PCF-License/LicenseFinder.git (push)
mic@ubuntu:~/vm/LicenseFinder$ rake
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/x86_64-linux
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/vendor_ruby/2.2.0
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/vendor_ruby/2.2.0/x86_64-linux
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/vendor_ruby
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/x86_64-linux
checking dev dependency for Maven ... missing `mvn`
checking dev dependency for NPM ... missing `npm`
checking dev dependency for Pip ... OK
checking dev dependency for Gradle ... missing `gradle`
checking dev dependency for Bower ... missing `bower`
checking dev dependency for Rebar ... missing `rebar`
checking dev dependency for Go ... missing `godep`

```

**Comment by mainej** [comment]
Looks like gems aren't being put on your loadpath.  Will you try replacing `require 'rspec/core/rake_task'`, and running with `bundle exec rake`?  If that works, you can [configure RVM](https://rvm.io/integration/bundler) so it doesn't need you to run `bundle exec` before everything.

**Comment by micfan** [comment]
I am sorry for mistaking `require`

**Comment by mainej** [comment]
No problem - I hope that fixed things!

**Pull request closed without merging**
