### PR TITLE
Add workarounds for projects using older erlang.mk versions

### PR DESCRIPTION
**Pull request by lukebakken**
Part of pivotal-cf/norsk-config#1167

cc @dumbbell @gerhard

### CODE REVIEW

**Comment by lukebakken** [comment]
@dumbbell @gerhard - I used this process to run Norsk reports locally:

Step-by-step instructions: https://github.com/pivotal-cf/norsk-config/wiki/Running-the-Norsk-Reports-Locally#example-setup

* Run the following:

```
mkdir ~/workspace
cd ~/workspace
git clone https://github.com/rabbitmq/rabbitmq-server-release.git
cd rabbitmq-server-release
git checkout v3.8.6
cd ..
git clone https://github.com/pivotal-cf/norsk.git
git clone https://github.com/pivotal-cf/norsk-config.git
cd norsk-config
git checkout lrb-rabbitmq-v3.8.5
```

* When container is up, follow these instructions: https://github.com/pivotal-cf/norsk-config/wiki/Running-the-Norsk-Reports-Locally#example-setup
* Then:

```
cd /LicenseFinder
git remote add rabbitmq https://github.com/rabbitmq/LicenseFinder.git
git fetch --all
git checkout lrb-handle-erlang.mk-error
cd /workspace/norsk
rake 'developer:report:generate_repo[/workspace/rabbitmq-server-release,rabbitmq-server-release,/workspace/norsk-config/releases/rabbitmq.yml,true]'
```

**Comment by dumbbell** [comment]
The test failure in https://norsk.cf-app.com/builds/821832 is a problem between mix(1) and Hex.pm. We hit the same problem a dozen times every day in RabbitMQ's CI...

I don't have the permission to retrigger the build in Concourse so I force-pushed to retrigger it.

**Comment by dumbbell** [comment]
We believe this PR is ready for review by the LicenseFinder team.

**Comment by xtreme-jason-smith** [comment]
Hi @dumbbell , overall it looks good. We just have two questions.

1. We noticed a couple of TODO's, but they don't seem to be actionable. Are they supposed to just be regular comments to explains the `IS_DEP=1`? If so, we don't need the TODO keyword, just regular comment will suffice.

2. For our knowledge, we assume that `query-deps` is supported for all erlang projects?

**Comment by dumbbell** [comment]
`query-deps` is supported by Erlang projects using Erlang.mk as their build system (another popular one is Rebar). Those projects also need to update to a very recent version of Erlang.mk because the `query-deps` feature was contributed by us for our CI and LicenseFinder use cases.

Yes, I can remove the `TODO` labels, indeed. We can't force other maintainers to use a newer Erlang.mk version.

**Comment by dumbbell** [comment]
If you are happy with the patch and once it is merged, could you please cut a new release of LicenseFinder? To be exact, we need this patch for the Tanzu RabbitMQ Norsk pipeline.

Our target is to release the first version of Tanzu RabbitMQ in September.

**Pull request merged**
