### PR TITLE
Fixup the dependency line matching

### PR DESCRIPTION
**Pull request by lukebakken**
I discovered this issue while running some tests. I must have always fetched deps before running LicenseFinder prior to these changes.

To reproduce prior to this PR, run the following command on the `master` branch:

```
cd ./features/fixtures/erlangmk
rm -rf .erlang.mk/ deps; git clean -fxd
bundle exec license_finder --project-path ./features/fixtures/erlangmk
```

Error:

```
$ bundle exec license_finder --project-path ./features/fixtures/erlangmk
LicenseFinder::Erlangmk: is active
bundler: failed to load command: license_finder (/home/lbakken/.gem/ruby/2.7.0/bin/license_finder)
InvalidErlangmkPackageError: 'DEP    rabbitmq_management (v3.8.5)' does not look like a valid Erlank.mk dependency. A valid dependency example: 'lager: goldrush git https://github.com/DeadZen/goldrush.git 0.1.9 /absolute/path/to/dep'
  /home/lbakken/development/rabbitmq/LicenseFinder/lib/license_finder/packages/erlangmk_package.rb:55:in `raise_invalid'
  /home/lbakken/development/rabbitmq/LicenseFinder/lib/license_finder/packages/erlangmk_package.rb:25:in `initialize'
  /home/lbakken/development/rabbitmq/LicenseFinder/lib/license_finder/package_managers/erlangmk.rb:26:in `new'
```

You will see an error concerning a line that begins with `DEP`. This is because the `--prepare` argument is not specified, so the `make QUERY=... query-deps` call out will actually fetch the deps, resulting in output that doesn't match the expectation for a dependency.

It can be fixed by...
* Adding the `--prepare` argument
* Applying this PR!

cc @xtreme-shane-lattanzio @gerhard

### CODE REVIEW

**Comment by lukebakken** [comment]
@xtreme-shane-lattanzio @gerhard ready for review (finally!)

**Comment by xtreme-shane-lattanzio** [comment]
@lukebakken Thanks! Do you think we should have a test for this new change?

**Comment by lukebakken** [comment]
Well, there are already tests but let me see if I can adjust the "fake output" to match what caused this issue in the first place.

**Comment by lukebakken** [comment]
@xtreme-shane-lattanzio :boom: 75b7696215641880061e1bc1cb2cf854ef052704

**Comment by lukebakken** [comment]
Thanks @xtreme-shane-lattanzio

**Pull request merged**
