### PR TITLE
Use elixir to parse mix pkg metadata at once

### PR DESCRIPTION
**Pull request by chulkilee**
`mix run -e "..."` has significant unnecessary overhead over `elixir -e "..."`. As the code does not need any Mix environment, just run them with `elixir` works.

### First change

- Run the same code with `elixir` instead of `mix run`
- Add `--elixir-command` option with default (`elixir`)

### Second change

- Preload all licenses at once

## Result

For 55 packages:

```
# before
license_finder --no-prepare  74.74s user 26.65s system 185% cpu 54.740 total

# after first change
license_finder --no-prepare  29.77s user 19.80s system 147% cpu 33.718 total

# after second change
license_finder --no-prepare  3.15s user 1.43s system 142% cpu 3.202 total
```

### CODE REVIEW

**Comment by xtreme-shane-lattanzio** [comment]
@chulkilee Thanks for the PR. CI is back up and running and there seems to be some failures. Can you take a look and then we can try to merge it in once fixed!

**Comment by chulkilee** [comment]
@xtreme-shane-lattanzio Seems like CI is still not working :(

**Comment by xtreme-shane-lattanzio** [comment]
@chulkilee Weird I don't see it here but it is here: https://norsk.cf-app.com/teams/main/pipelines/LicenseFinder-pr/jobs/PR-ruby-2.6.1-linux/builds/56

**Comment by xtreme-shane-lattanzio** [comment]
@chulkilee Status is reported again here. It will only report on failure or success.

**Comment by xtreme-shane-lattanzio** [comment]
Hey @chulkilee Sorry about the CI on this PR. Not sure why it is not properly reporting. The latest build is here: https://norsk.cf-app.com/teams/main/pipelines/LicenseFinder-pr/jobs/PR-ruby-2.6.1-linux/builds/63. Any idea why `elixir_command` is missing in the failing tests?

**Comment by xtreme-shane-lattanzio** [comment]
@chulkilee Okay I think I figured it out. You are force pushing causing CI to pick up the wrong code. I forced it to rerun and see the proper errors here: https://norsk.cf-app.com/teams/main/pipelines/LicenseFinder-pr/jobs/PR-ruby-2.6.1-linux/builds/65

**Comment by chulkilee** [comment]
Hm I see. I'd prefer not to have any merge commit - so I rebase my branch with the up-to-date master. The CI should be fixed to handle that!

**Comment by chulkilee** [comment]
Rebased and force pushed. @xtreme-shane-lattanzio could you take a look? Not sure it still needs manual trigger

**Comment by xtreme-shane-lattanzio** [comment]
@chulkilee Looks like there are still some failures here: https://norsk.cf-app.com/teams/main/pipelines/LicenseFinder-pr/jobs/PR-ruby-2.6.3-linux/builds/6

**Comment by chulkilee** [comment]
@xtreme-shane-lattanzio that's not the latest commit in the branch. Anyway, I pushed the fix

**Comment by xtreme-shane-lattanzio** [comment]
@chulkilee I feel like we are going back and forth between two errors :( We have seen this one before.

**Comment by chulkilee** [comment]
Pushed new commit, with small fix (handle when `deps` directory does not exists).

Could you check out CI when it's done?

**Comment by chulkilee** [comment]
@xtreme-shane-lattanzio  seems like CI is stuck again :(

**Comment by xtreme-shane-lattanzio** [comment]
Hey @chulkilee ! Looks good now except for a rubocop correction can you fix that and then we can have this merged? Thanks so much for keeping up with this :)

**Comment by xtreme-shane-lattanzio** [comment]
Bumping for webhook trigger.

**Comment by pivotal-issuemaster** [comment]
@chulkilee Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=594)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=594) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@chulkilee Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=594)!

**Pull request merged**
