### PR TITLE
Add support Scala Build Tool (sbt)

### PR DESCRIPTION
**Pull request by bradfordboyle**
- Add `sbt_include_groups` option
- Update README.md to include Scala/sbt

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@bradfordboyle Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=468)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=468) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by xtreme-shane-lattanzio** [comment]
@bradfordboyle We took at look at your failures and this is not an issue with your code. 

The 2.1.5 issue was an html url having an underscore in a spec file instead of a dash
https://github.com/pivotal/LicenseFinder/commit/f2e6238b2b5ee149cf4b40ba4c8759f97a3dc043

The 2.2.0 issue was due to rack-test not being locked to version 0.7.0. The new version 0.8.3 requires ruby 2.2.2 to function. This is now locked in the license_finder.gemspec.

The jruby issue was the hard one. Scala needs to be run with JDK 1.8 but the docker image seemed to be using 1.7. We now have conitions that force 1.8 to be used when running with jruby.

Please see PR: https://github.com/pivotal/LicenseFinder/pull/470 for the relevant code changes. You will need to rebase your branch off master after it has been merged in.

**Comment by bradfordboyle** [comment]
@xtreme-shane-lattanzio Thanks for looking into this. I just rebased, so CI should be going green soon.

**Comment by xtreme-shane-lattanzio** [comment]
@bradfordboyle And green it is! We just need to get you to sign the pivotal-cla and we can merge it in. Thanks for rebasing everything.

**Comment by pivotal-issuemaster** [comment]
@bradfordboyle Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=468)!

**Pull request merged**
