### PR TITLE
Use bundle gemfile env to specify gemfile

### PR DESCRIPTION
**Pull request by brandonduff**
Addresses #508

### CODE REVIEW

**Comment by brandonduff** [comment]
It looks like CI is having trouble building the docker image. I get the same error when trying to build the docker image locally on master.

It looks like it's having trouble grabbing the JDK from Oracle. Here's the output of the `wget` without the `--quiet` option on my machine:
```
wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" https://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.tar.gz -O jdk-8.tgz

--2019-04-25 10:50:05--  https://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.tar.gz
Resolving download.oracle.com (download.oracle.com)... 23.59.156.156
Connecting to download.oracle.com (download.oracle.com)|23.59.156.156|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://edelivery.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.tar.gz [following]
--2019-04-25 10:50:05--  https://edelivery.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.tar.gz
Resolving edelivery.oracle.com (edelivery.oracle.com)... 23.56.112.136
Connecting to edelivery.oracle.com (edelivery.oracle.com)|23.56.112.136|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.tar.gz?AuthParam=1556211125_0812195e6f58bb5a7ad08cfa1809bf44 [following]
--2019-04-25 10:50:05--  http://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.tar.gz?AuthParam=1556211125_0812195e6f58bb5a7ad08cfa1809bf44
Connecting to download.oracle.com (download.oracle.com)|23.59.156.156|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.tar.gz?AuthParam=1556211125_0812195e6f58bb5a7ad08cfa1809bf44 [following]
--2019-04-25 10:50:05--  https://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.tar.gz?AuthParam=1556211125_0812195e6f58bb5a7ad08cfa1809bf44
Connecting to download.oracle.com (download.oracle.com)|23.59.156.156|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-04-25 10:50:06 ERROR 404: Not Found.
```

**Comment by osis** [comment]
@brandonduff I'm getting the same error locally. Looks like we'll have to PR an update to that link.

**Comment by osis** [comment]
@brandonduff, sorry for the inconvenience, can you rebase this PR against master to kick off a new CI testing cycle?

**Comment by brandonduff** [comment]
Thanks for updating that!

We have a build, but it looks like https://github.com/pivotal-legacy/LicenseFinder/pull/567 may have broken this implementation. I'll have to dig into this a little more when I have some time.

**Comment by osis** [comment]
Thanks a ton!

**Comment by xtreme-shane-lattanzio** [comment]
Hey @brandonduff Bumping this. We have since fixed the result of #567 but it looks like there is one failure on CI for this PR. Not really sure of the output that you wanted so can you take a look when you have a chance and we can merge this in? Thanks!!

**Comment by brandonduff** [comment]
I'll take a look at this later this week. It seems https://github.com/pivotal/LicenseFinder/blob/master/lib/license_finder/package_managers/bundler.rb#L41 kind of conflicts with the intent of this, so I'll have to see if I can resolve the two.

**Comment by xtreme-shane-lattanzio** [comment]
Bumping for webhook trigger.

**Comment by pivotal-issuemaster** [comment]
@brandonduff Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=572)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=572) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Pull request merged**
