### PR TITLE
Document breaking changes

### PR DESCRIPTION
**Pull request by dakotahp**
I'm baffled that major breaking changes were slipped into a release without being documented or added to the changelog. Bad form. I've gone ahead and done this for you so others don't waste their valuable time like I did.

Links to both the commit and PR for greater context since the PR had two commits.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@dakotahp Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=693)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=693) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@dakotahp Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=693)!

**Comment by dakotahp** [comment]
Correction, it's listed under 6.0.0 https://github.com/pivotal/LicenseFinder/blob/master/CHANGELOG.md#600--2020-01-22 🤷🏼‍♂️I can close this or move it if the attribution is incorrect.

**Comment by dakotahp** [comment]
GitHub's UI for the diff of release always confuses me. My mistake, this is documented correctly and under the right version 🤦🏼‍♂️I'm dumb.

image

**Pull request closed without merging**
