### PR TITLE
Don't override the user's BUNDLE_PATH incorrectly

### LINKED ISSUE #615: error when gem points to a git repo
Running license finder fails when the Gemfile has a gem that points to a git repo.

Example Gemfile:
```
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'loaf', git: 'https://github.com/piotrmurach/loaf.git'
```

Error log:

```
$ license_finder report --project-path=/tmp/example-project --prepare
LicenseFinder::Bundler: is active
Traceback (most recent call last):
	34: from /usr/share/rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
	33: from /usr/share/rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
	32: from /usr/share/rvm/gems/ruby-2.6.3/bin/license_finder:23:in `<main>'
	31: from /usr/share/rvm/gems/ruby-2.6.3/bin/license_finder:23:in `load'
	30: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/bin/license_finder:6:in `<top (required)>'
	29: from /usr/share/rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	28: from /usr/share/rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	27: from /usr/share/rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	26: from /usr/share/rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	25: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/cli/main.rb:139:in `report'
	24: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/license_aggregator.rb:11:in `dependencies'
	23: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/license_aggregator.rb:49:in `aggregate_packages'
	22: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/license_aggregator.rb:49:in `flat_map'
	21: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/license_aggregator.rb:49:in `each'
	20: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/license_aggregator.rb:51:in `block in aggregate_packages'
	19: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/forwardable.rb:224:in `acknowledged'
	18: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/core.rb:78:in `decision_applier'
	17: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/core.rb:83:in `current_packages'
	16: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/scanner.rb:17:in `active_packages'
	15: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/scanner.rb:17:in `flat_map'
	14: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/scanner.rb:17:in `each'
	13: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/package_manager.rb:97:in `current_packages_with_relations'
	12: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/package_managers/bundler.rb:15:in `current_packages'
	11: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/package_managers/bundler.rb:47:in `details'
	10: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/package_managers/bundler.rb:62:in `gem_details'
	 9: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/definition.rb:237:in `specs_for'
	 8: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/definition.rb:170:in `specs'
	 7: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/spec_set.rb:81:in `materialize'
	 6: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/spec_set.rb:81:in `map!'
	 5: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/spec_set.rb:84:in `block in materialize'
	 4: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/lazy_specification.rb:76:in `__materialize__'
	 3: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/source/git.rb:167:in `specs'
	 2: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/source/path.rb:100:in `local_specs'
	 1: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/source/git.rb:200:in `load_spec_files'
/usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/source/path.rb:198:in `load_spec_files': The path `/tmp/example-project/bundler/gems/loaf-001dfad83616` does not exist. (Bundler::PathError)
	34: from /usr/share/rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
	33: from /usr/share/rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
	32: from /usr/share/rvm/gems/ruby-2.6.3/bin/license_finder:23:in `<main>'
	31: from /usr/share/rvm/gems/ruby-2.6.3/bin/license_finder:23:in `load'
	30: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/bin/license_finder:6:in `<top (required)>'
	29: from /usr/share/rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	28: from /usr/share/rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	27: from /usr/share/rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	26: from /usr/share/rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	25: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/cli/main.rb:139:in `report'
	24: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/license_aggregator.rb:11:in `dependencies'
	23: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/license_aggregator.rb:49:in `aggregate_packages'
	22: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/license_aggregator.rb:49:in `flat_map'
	21: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/license_aggregator.rb:49:in `each'
	20: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/license_aggregator.rb:51:in `block in aggregate_packages'
	19: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/forwardable.rb:224:in `acknowledged'
	18: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/core.rb:78:in `decision_applier'
	17: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/core.rb:83:in `current_packages'
	16: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/scanner.rb:17:in `active_packages'
	15: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/scanner.rb:17:in `flat_map'
	14: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/scanner.rb:17:in `each'
	13: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/package_manager.rb:97:in `current_packages_with_relations'
	12: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/package_managers/bundler.rb:15:in `current_packages'
	11: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/package_managers/bundler.rb:47:in `details'
	10: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/package_managers/bundler.rb:62:in `gem_details'
	 9: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/definition.rb:237:in `specs_for'
	 8: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/definition.rb:170:in `specs'
	 7: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/spec_set.rb:81:in `materialize'
	 6: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/spec_set.rb:81:in `map!'
	 5: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/spec_set.rb:84:in `block in materialize'
	 4: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/lazy_specification.rb:76:in `__materialize__'
	 3: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/source/git.rb:167:in `specs'
	 2: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/source/path.rb:100:in `local_specs'
	 1: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/source/git.rb:199:in `load_spec_files'
/usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/source/git.rb:203:in `rescue in load_spec_files': https://github.com/piotrmurach/loaf.git (at master@001dfad) is not yet checked out. Run `bundle install` first. (Bundler::GitError)
```

### PR DESCRIPTION
**Pull request by Haegin**
Fixes #615 

The bundler directory is unlikely to be the project path as bundle defaults to storing gems in the default gem storage location unless it's run with the `--deployment` option.

### CODE REVIEW

**Comment by xtreme-shane-lattanzio** [comment]
@Haegin I think there is more that we need to think about when considering this change. There was a PR and a bunch of linked issues back in March that started with a desired fix when `bundle install --path` option is used. See the work and conversation here: https://github.com/pivotal/LicenseFinder/pull/558

There was also some reverting and tweaking going on because it did break our pipelines at one point: https://github.com/pivotal/LicenseFinder/pull/567

There is also a similar idea I think you are thinking about here regarding gemfile path instead of bundle path. There was a PR to make the path more dynamic here: https://github.com/pivotal/LicenseFinder/pull/572

We may want to take an approach that is more like that as the project path as a default should work in most cases. Take a look and let me know what you think!

**Comment by pivotal-issuemaster** [comment]
@Haegin Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=620)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=620) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Haegin Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=620)!

**Comment by xtreme-shane-lattanzio** [comment]
Gonna close this due to inactivity. Reopen if further investigation happens!

**Pull request closed without merging**
