### PR TITLE
Fix in_umbrella: true dependencies

### LINKED ISSUE #475: Mix in_umbrella: true dependencies mix deps output is parsed incorrectly
`LicenseFinder::Mix` assumes that if a package has a starting line with `* NAME`, then it will have either a `locked at` line or a `the dependency is not available` line, but this is not the case for `in_umbrella: true` dependencies, which only have the `ok` line that signals the end of the packages lines.

3 known formats are

1. Hex package that is installed

```
* mimerl 1.0.2 (Hex package) (rebar3)
  locked at 1.0.2 (mimerl) 993f9b0e
  ok
```

2. Hex package that is not installed, but is locked

```
* bunt (Hex package) (mix)
  locked at 0.2.0 (bunt) 951c6e80
  the dependency is not available, run "mix deps.get"
```

3. `in_umbrella: true` dependency, which is in a directory under `apps`

```
* explorer 0.0.1 (apps/explorer) (mix)
  ok
```

(1) and (2) have 3 lines, but (3) only has 2 lines, which causes the `select` and `each_slice` 

https://github.com/pivotal/LicenseFinder/blob/0efa65b9cbae6000d3fcbe88d6e0674e77973b42/lib/license_finder/package_managers/mix.rb#L42-L43

to [incorrectly group lines to the wrong package or wrong part of the dependency description](https://circleci.com/gh/poanetwork/poa-explorer/349)

```
Dependencies that need approval:
at, "* explorer_web 0.0.1 (apps/explorer_web) (mix)", unknown
explorer, "* phoenix_ecto 3.3.0 (Hex package) (mix)", unknown
```

### PR DESCRIPTION
**Pull request by KronicDeth**
Fixes #475

Don't assume that all dependencies have the same number of lines and instead group package lines together first and then extract the name and version for each package.  `in_umbrella: true` dependencies are completely ignored since they will be under the project's license and are not true dependencies.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@KronicDeth Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=476)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=476) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@KronicDeth Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/LicenseFinder&pullRequestId=476)!

**Comment by kdykeman** [comment]
It looks like this comment was added to #475 rather than the PR - copying here:

@KronicDeth thanks for the PR. Can you add a test for this scenario in the [mix_spec]?(https://github.com/pivotal/LicenseFinder/blob/master/spec/lib/license_finder/package_managers/mix_spec.rb)

**Comment by KronicDeth** [comment]
@kdykeman don't worry, I still saw the comment since I opened the issue and was already working on adding a mix umbrella project test.

**Pull request merged**
